[package]
name = "db_testcontainer"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
