[package]
name = "entity"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
sea-orm.workspace = true

[lints]
workspace = true
