[package]
name = "appstate"
authors.workspace = true
edition.workspace = true
version.workspace = true
license-file = "../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal dependencies
db.workspace = true
settings.workspace = true
storage.workspace = true
common.workspace = true

# External dependencies
axum.workspace = true
axum-extra.workspace = true
flume.workspace = true
