[package]
name = "common"
version = "0.1.0"
edition.workspace = true
license-file = "../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# External dependencies from crates.io
alkali.workspace = true
axum.workspace = true
rand.workspace = true
regex.workspace = true
sea-orm.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha256.workspace = true
thiserror.workspace = true
tokio.workspace = true
reqwest.workspace = true
tracing.workspace = true

[lints]
workspace = true
