[package]
name = "common"
version = "0.1.0"
edition.workspace = true
license-file = "../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal dependencies from Kellnr

# External dependencies from crates.io
anyhow.workspace = true
serde.workspace = true
semver.workspace = true
regex.workspace = true
serde_json.workspace = true
rand.workspace = true
sea-orm.workspace = true
axum.workspace = true
tokio.workspace = true
