[package]
name = "error"
authors.workspace = true
edition.workspace = true
version.workspace = true
license-file = "../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal dependencies
common.workspace = true
db.workspace = true

# External dependencies
zip.workspace = true
serde.workspace = true
anyhow.workspace = true
axum.workspace = true
