[package]
name = "settings"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE"

[dependencies]
# External dependencies from crates.io
config.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
