[package]
name = "settings"
version = "0.1.0"
edition.workspace = true
license-file = "../../LICENSE"

[dependencies]
# External dependencies from crates.io
config.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
toml.workspace = true
serde_json.workspace = true
